version: "3"

services:
  app:
    container_name: 'fastify'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - "/app/node_modules"
      - "./logs:/var/log"
    depends_on:
      - mysql_server

  mysql_server:
    container_name: 'db-apps'
    # image: mysql:5.7.22
    image: mariadb
    ports:
      - "3307:3306"
    volumes:
      - ./data-mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
